description: "This is a sample config to run the pipeline"
# workdir: "" #relative to `respr` directory
model:
  name: "MultiparameterSmartFusion2"
  args: []
  kwargs:
    config: {}
data_adapter:
  name: "BidmcDataAdapter"
  args: []
  kwargs:
    config:
      data_root_dir: "../../Datasets/bidmc-ppg-and-respiration-dataset-1.0.0/bidmc_csv"