description: "This is a sample config to run the pipeline"
# output_dir: "../../artifacts/store/frozen/dataset_capnobase_w32_s4_fs_final_25Hz_artif_cleaned_gt_mean"
output_dir: "../../artifacts/store/frozen/dataset_bidmc_w32_s4_fs_final_300Hz_raw"
# workdir: "" #relative to `respr` directory
# pipeline:
#   name: "DatasetBuilder"
# instructions:
#   sample_index_offset: 0
#   num_samples_to_process: 2 # if None then all samples are processed and
#   # `sample_idx_offset` is ignore (not used)
#   exclude_artifacts: true


pipeline:
  name: "DatasetBuilder" # some of the instructions below are not ussed by `DatasetBuilder` pipeline
instructions:
  subject_id_prefix: "bidmc_"
  signals_to_include: raw # raw, all_induced, all
  window_duration: 32 # in seconds
  window_step_duration: 4 # window stride in seconds
  expected_signal_duration: 480 # total length of signal in seconds (for assertion)
  vector_length: 9600 # desired vector length (used for assertion) / and in case the
  # the signal needs to be resampled it is used as the number of points
  resample_ppg: false 
  # NOTE: this flag is fore resampling before processing
  resampling_frequency: null # used only if `resample_ppg` is set
  resample_output_ppg: 300 #null # This is for resampling after the processing is done
  # The output vector size will depend on this, if it is provided (i.e. when 
  # it is not `null`). Its value is treated as resampling frequency
  sample_index_offset: 0
  num_samples_to_process: null # if None then all samples are processed and
  # `sample_idx_offset` is ignore (not used)
  exclude_artifacts: true
  ground_truth_mode: "mean" # indicates how the underlying signal processor
  # should compute the ground truth respiratory rate for signal windows.
  # e.g. `mean` => mean value over the window, `mid` =>" take label at 
  # the middle of the window"
  
model:
  name: "MultiparameterSmartFusion"
  args: []
  kwargs:
    config:
      resp_rate_cutoff_high: 90 # in breaths per min. Used for removing non-respiratory frequencies
      resp_rate_cutoff_low: 2
# data_adapter:
#   name: "CapnobaseMatDataAdapter"
#   args: []
#   kwargs:
#     config:
#       data_root_dir: "../../Datasets/capnobase-dataverse/data/mat"
data_adapter:
  name: "BidmcDataAdapter"
  args: []
  kwargs:
    config:
      data_root_dir: "../../Datasets/\
        bidmc-ppg-and-respiration-dataset-1.0.0/bidmc_csv"
