pipeline:
  name: "EvalPipeline"
output_dir: "../../artifacts/_eval/FINAL"
__selected_experiments: # list of ( tuple (tag:str, list of (experiment_ids:str)))
  - ["001", ["SF004", "12", "20P"]]
  - ["002", ["SF004", "20O", "20P"]]
  - ["002_b", ["SF004", "12", "20O"]]
  - ["003_bidmc", ["SF003", "20Q"]]
  - ["004", ["SF004", "12", "12_run2"]]
  # - ["capno_SF", ["SF004", "SF004-TYPE_2B"]]
  # - ["BIDMC_SF", ["SF003", "SF003-TYPE_2B"]]
  # - ["all", ["SF004", "12", "12L", "20E", "20F", "20G", "20H", "20I", "20J", "20M", "20N"]]
  # - ["C", [ "20M", "20N"]]
  # - ["D", ["SF004", "12", "26B"]]
  # - ["E", ["SF004", "12", "20G"]]
  # - ["A", [ "SF004", "20G", "20M", "20N"]]
  # - ["B", ["20F", "20G", "20M", "20N"]]
  # - ["20s", ["26B", "20E", "20F", "20G", "20H", "20I", "20J", "20M", "20N"]]
  # - ["set_01", ["SF004", "12", "12L"]]
  # - ["set_02", ["SF004", "12", "12_run2"]]
  # - ["12_run2", ["12_run2"]]
  # - ["12L", [ "12L"]]
  # - ["12", ["12"]]
  # - ["SF004", ["SF004"]]
  # - ["set_03", ["SF004", "20M", "20N"]]

selected_experiments:
  - ["SF003", ["SF003"]]
  - ["SF004", ["SF004"]]
  - ["12", ["12"]]
  - ["20P", ["20P"]]
  - ["20", ["20"]]
  - ["20b", ["20b"]]
  - ["22c2", ["22c2"]]
  - ["20C", ["20C"]]
  - ["20C-set02", ["20C-set02"]]
  - ["20D", ["20D"]]
  - ["20E", ["20E"]]
  - ["20F", ["20F"]]
  - ["20G", ["20G"]]
  - ["20H", ["20H"]]
  - ["20I", ["20I"]]
  - ["20J", ["20J"]]
  - ["20K", ["20K"]]
  - ["20L", ["20L"]]
  - ["20M", ["20M"]]
  - ["20N", ["20N"]]
  - ["20O", ["20O"]]
  - ["20P", ["20P"]]
  - ["20Q", ["20Q"]]
  - ["25", ["25"]]
  - ["25A", ["25A"]]
  - ["26", ["26"]]
  - ["12_1a_bidmc", ["12_1a"]]
  - ["26B", ["26B"]]
  - ["26C_bidmc", ["26C", "12_1a"]]
  - ["26C_bidmc", ["26C"]]
  - ["SF003-TYPE_2B", ["SF003-TYPE_2B"]]
  - ["SF007", ["SF007"]]