description: "This is a sample config to run the pipeline"
# workdir: "" #relative to `respr` directory
# pipeline:
#   name: "DatasetBuilder"
# instructions:
#   sample_index_offset: 0
#   num_samples_to_process: 2 # if None then all samples are processed and
#   # `sample_idx_offset` is ignore (not used)
#   exclude_artifacts: true


pipeline:
  name: "IndexedDatasetBuilder"
instructions:
  window_duration: 32 # in seconds
  window_step_duration: 1 # window stride in seconds
  expected_signal_duration: 480 # total length of signal in seconds (for assertion)
  vector_length: 9600 # desired vector length (used for assertion) / and in case the
  # the signal needs to be resampled it is used as the number of points
  resample_ppg: False # `False` for Capnobase / `True` for BIDMC (which is @125Hz)
  resampling_frequency: 300 # used only if `resample_ppg` is set
  sample_index_offset: 0
  num_samples_to_process: null # if None then all samples are processed and
  # `sample_idx_offset` is ignore (not used)
  exclude_artifacts: true
  dataset_id: "capnobase-win32-stride1-resp-mid-full-normalized"
  normalize_ppg: True
  ground_truth_mode: "mid" # indicates how the underlying signal processor
  # should compute the ground truth respiratory rate for signal windows.
  # e.g. `mean` => mean value over the window, `mid` =>" take label at 
  # the middle of the window"
  
model:
  name: "MultiparameterSmartFusion"
  args: []
  kwargs:
    config:
      resp_rate_cutoff_high: 90 # in breaths per min. Used for removing non-respiratory frequencies
      resp_rate_cutoff_low: 2
data_adapter:
  name: "CapnobaseMatDataAdapter"
  args: []
  kwargs:
    config:
      data_root_dir: "../../Datasets/capnobase-dataverse/data/mat"
# data_adapter:
#   name: "CapnobaseMatDataAdapter"
#   args: []
#   kwargs:
#     config:
#       data_root_dir: "../../Datasets/bidmc-ppg-and-respiration-dataset-1.0.0/bidmc_csv"
