description: "This is a sample config to run the pipeline"

pipeline:
  name: "TrainingPipeline"
instructions:
  do_only_test: false # make sure to set `ckpt_path`
  ckpt_path:
    3: ../../artifacts/2022-11-24_150935/fold_00/lightning_logs/version_0/checkpoints/model-epoch=00-s-step=1-val_mae=9.01.ckpt
    4: ../../artifacts/2022-11-24_150935/fold_00/lightning_logs/version_0/checkpoints/model-epoch=00-s-step=2-val_mae=10.30.ckpt
    

#checkpointing # monitor param etc. goes under this attribute


trainer: # currently using trainer from pytorch lightning 
  name: null
  args: []
  kwargs:
    max_epochs: 30
    # not use `check_val_every_n_epoch` if using `val_check_interval`
    # check_val_every_n_epoch: 1
    val_check_interval: 0.25 
    # fast_dev_run: true # for debugging only
    # limit_train_batches: 0.01 # for debugging only
    # overfit_batches=0.01 # for debugging only
    enable_progress_bar: true
    overfit_batches: 5 #batches
    # resume_from_checkpoint: null
    # <<< FOR GPU >>>
    # accelerator: gpu
    # devices: 1


model: # model => actual model + lighting wrapper
  name: "LitResprMCDropoutCNN"
  args: []
  kwargs:
    config:
      optimization:
        lr: 1.0e-3
        weight_decay: 1.0e-4
      model_module_class: ResprMCDropoutCNN
      module_config: # config for the actual pytorch model
      # it will be passed as config kwarg like so `model_module(config=...)`
        input_channels: 4
        force_reshape_input: false
      y_normalization: # added in new #TODO: use this entry
        y_mean: 0.
        y_std: 1.0




dataloading:
  name: "ResprCsvDataLoaderComposer"
  args: []
  kwargs:
    # config:
      # dataset: "BaseResprCsvDataset"
      # dataset_path: "../../artifacts/frozen/dataset_capnobase_w32_s1_artif_cleaned_commit_c4dec47.csv"
      # batch_size: 16
      # num_workers: 0
      # augmentation: null # to be added later #TODO
      # num_folds: 5
      # start_fold: 0
      # val_split: 0.2
      # test_split: 0.2
      # ckpt_path: ../../artifacts/2022-11-17_050120/fold_00/lightning_logs/version_2482287/checkpoints/epoch=7-step=6717.ckpt
    # MINI DATASET FOR DEV
    config:
      dataset: "ResprAllSignalsCsvDataset"
      dataset_path: "../../artifacts/frozen/2022-12-07_000441/dataset.csv"
      x_length: 9984 # dimension of input x
        # sample paths
        #"../../artifacts/frozen/2022-12-07_000441/dataset.csv"
      normalize_x: false 
      batch_size: 2
      augmentation: null # to be added later #TODO
      num_folds: 2
      start_fold: 0
      val_split: 0.25
      test_split: 0.25
      num_workers: 0



# data_adapter:
#   name: "CapnobaseMatDataAdapter"
#   args: []
#   kwargs:
#     config:
#       data_root_dir: "../../Datasets/bidmc-ppg-and-respiration-dataset-1.0.0/bidmc_csv"
