description: This is a sample config to run the pipeline\
  [SmartFusion on capnobase, w16 s4]
output_dir: "../../artifacts/frozen/smartfusion_result/capnobase_w16_s4_gt_mean"
data_adapter:
  args: []
  kwargs:
    config:
      data_root_dir: ../../Datasets/capnobase-dataverse/data/mat
  name: CapnobaseMatDataAdapter
instructions:
  exclude_artifacts: true
  expected_signal_duration: 480
  ground_truth_mode: mean
  num_samples_to_process: null
  sample_index_offset: 0
  window_duration: 16
  window_step_duration: 4
  window_type: hamming
model:
  args: []
  kwargs:
    config:
      resp_rate_cutoff_high: 90
      resp_rate_cutoff_low: 2
      butterworth_filter_order: 4
  name: MultiparameterSmartFusion
pipeline:
  name: Pipeline2
window_type: hamming
