description: "This is a sample config to run the pipeline"
output_dir: "../../artifacts/exp_15_cnn_on_w32_s16_mean_gt_induced_signal_LOOCV"
pipeline:
  name: "TrainingPipeline"
instructions:
  do_only_test: false # make sure to set `ckpt_path`

trainer: # currently using trainer from pytorch lightning 
  name: null
  args: []
  kwargs:
    max_epochs: 20
    # not use `check_val_every_n_epoch` if using `val_check_interval`
    # check_val_every_n_epoch: 1
    val_check_interval: 0.25 
    # fast_dev_run: true # for debugging only
    # limit_train_batches: 0.01 # for debugging only
    # overfit_batches=0.01 # for debugging only
    enable_progress_bar: true
    # overfit_batches: 5 #batches
    # resume_from_checkpoint: null
    # <<< FOR GPU >>>
    accelerator: gpu
    devices: [0]


model:
  name: "LitResprResnet18"
  args: []
  kwargs:
    config:
      optimization:
        lr: 1.0e-3
        weight_decay: 1.0e-4
      module_config: # config for the actual pytorch model
      # it will be passed as config kwarg like so `model_module(config=...)`
        input_channels: 3
        force_reshape_input: True

dataloading:
  name: "ResprCsvDataLoaderComposer"
  args: []
  kwargs:
    # config:
      # dataset: "BaseResprCsvDataset"
      # dataset_path: "../../artifacts/frozen/dataset_capnobase_w32_s1_artif_cleaned_commit_c4dec47.csv"
      # batch_size: 16
      # num_workers: 0
      # augmentation: null # to be added later #TODO
      # num_folds: 5
      # start_fold: 0
      # val_split: 0.2
      # test_split: 0.2
      # ckpt_path: ../../artifacts/2022-11-17_050120/fold_00/lightning_logs/version_2482287/checkpoints/epoch=7-step=6717.ckpt
    # MINI DATASET FOR DEV
    config:
      dataset: "BaseResprCsvDataset"
      dataset_path: "../../artifacts/frozen/2022-12-01_235401-commit-w32s16\
        -mean-gt-bc3c31d08/dataset_capnobase_all_induced_w32_s32_artif_\
        cleaned_gt_mean_commit-bc3c31d08.csv"
      # >>> new config attrs added to support trainingin on RIAV RIFV RIIV>>>
      x_length: 384 # dimension of input x
      normalize_x: false
      # <<<<

      batch_size: 16
      augmentation: null # to be added later #TODO
      num_folds: 22 # do for 42
      start_fold: 0
      val_split: 0.2
      test_split: 0.023 # ~1/42
      num_workers: 0



# data_adapter:
#   name: "CapnobaseMatDataAdapter"
#   args: []
#   kwargs:
#     config:
#       data_root_dir: "../../Datasets/bidmc-ppg-and-respiration-dataset-1.0.0/bidmc_csv"
